--Punto 1
CREATE OR REPLACE VIEW MEDIOS_PAGO_CLIENTES AS
  SELECT  DISTINCT CLIENTES.ID AS CLIENTES_ID
  ,(CLIENTES.NOMBRE  || ' ' || CLIENTES.APELLIDOS) AS NOMBRE_CLIENTE
  ,MEDIOS_DE_PAGO.ID AS MEDIO_PAGO_ID
  ,TIPOS_DE_PAGO.NOMBRE AS TIPO
  ,MEDIOS_DE_PAGO.DATOS AS DETALLES_MEDIO_PAGO
  ,CLIENTES.EMPRESA AS EMPRESARIAL
  ,CASE CLIENTES.EMPRESA WHEN 'FALSO' THEN NULL ELSE CLIENTES.NOMBRE_EMPRESA END AS NOMBRE_EMPRESA
  FROM CLIENTES
  INNER JOIN MEDIOS_DE_PAGO
  ON CLIENTES.ID = MEDIOS_DE_PAGO.ID_CLIENTE
  INNER JOIN TIPOS_DE_PAGO
  ON MEDIOS_DE_PAGO.ID_TIPO_PAGO = TIPOS_DE_PAGO.ID;


--Punto 2
  CREATE OR REPLACE VIEW VIAJES_CLIENTES AS
  SELECT VIAJES.FECHAVIAJE AS FECHA_VIAJE
  ,DRIVERS.NAME AS NOMBRE_CONDUCTOR
  ,VEHICULOS.PLACA AS PLACA_VEHICULO
  ,(CLIENTES.NOMBRE  || ' ' || CLIENTES.APELLIDOS) AS NOMBRE_CLIENTE
  ,FACTURAS.VALORNETO AS VALOR_TOTAL 
  ,VIAJES.TARIFA_DINAMICA 
  ,TYPE_OF_SERVICES.DESCRIPTION AS TIPO_SERVICIO
  ,CIUDADES.NOMBRE AS CIUDAD_VIAJE
  FROM VIAJES
  INNER JOIN DRIVERS
  ON VIAJES.ID_CONDUCTORVEHICULO = DRIVERS.ID
  INNER JOIN VEHICULOS
  ON VEHICULOS.ID_CONDUCTOR = DRIVERS.ID
  INNER JOIN CLIENTES
  ON CLIENTES.ID = ID_CLIENTE
  INNER JOIN FACTURAS
  ON FACTURAS.ID_CLIENTE = CLIENTES.ID
  INNER JOIN TYPE_OF_SERVICES
  ON TYPE_OF_SERVICES.ID = VIAJES.ID_TIPOSERVICIO
  INNER JOIN CIUDADES
  ON CIUDADES.ID = VIAJES.ID_CIUDAD
  ORDER BY VIAJES.FECHAVIAJE;
 
 
--Puntos 3 
 EXPLAIN PLAN FOR
  SELECT VIAJES.FECHAVIAJE AS FECHA_VIAJE
  ,DRIVERS.NAME AS NOMBRE_CONDUCTOR
  ,VEHICULOS.PLACA AS PLACA_VEHICULO
  ,(CLIENTES.NOMBRE  || ' ' || CLIENTES.APELLIDOS) AS NOMBRE_CLIENTE
  ,FACTURAS.VALORNETO AS VALOR_TOTAL 
  ,VIAJES.TARIFA_DINAMICA 
  ,TYPE_OF_SERVICES.DESCRIPTION AS TIPO_SERVICIO
  ,CIUDADES.NOMBRE AS CIUDAD_VIAJE
  FROM VIAJES
  INNER JOIN DRIVERS
  ON VIAJES.ID_CONDUCTORVEHICULO = DRIVERS.ID
  INNER JOIN VEHICULOS
  ON VEHICULOS.ID_CONDUCTOR = DRIVERS.ID
  INNER JOIN CLIENTES
  ON CLIENTES.ID = ID_CLIENTE
  INNER JOIN FACTURAS
  ON FACTURAS.ID_CLIENTE = CLIENTES.ID
  INNER JOIN TYPE_OF_SERVICES
  ON TYPE_OF_SERVICES.ID = VIAJES.ID_TIPOSERVICIO
  INNER JOIN CIUDADES
  ON CIUDADES.ID = VIAJES.ID_CIUDAD
  ORDER BY VIAJES.FECHAVIAJE;
  
  
   SELECT * FROM TABLE (DBMS_XPLAN.DISPLAY);

   CREATE INDEX "INDICE" ON "FACTURAS" ("VALORNETO"); 
   CREATE INDEX "INDICE_FECHA" ON "VIAJES" ("FECHAVIAJE"); 
 